Feature/homework 1
hellbeemzk/FocusStartHomeworks pull request #1
Opened 2021-11-01 07:31 UTC by hellbeemzk

Реализован функционал программы:
1 - Добавить автомобиль в список 
2 - Вывести список всех добавленных автомобилей
3 - Вывести список отфильтрованых по кузову автомобилей 
4 - Выход

2021-11-01 16:17 UTC, AlexRaptor requested changes

2021-11-01 16:17 UTC, AlexRaptor commented on homework1/homework1/main.swift
> +        startMenu()
- [ ] Баг

Тут мы войдём в меню, а когда выберем "Выход", то не выйдем здесь и продолжим выполнение метода и опять войдём в меню

2021-11-01 16:17 UTC, AlexRaptor commented on homework1/homework1/main.swift
> +        startMenu()
сколько раз попробуем вывести пустой список, столько раз потом придётся жмакать "Выход"

2021-11-01 16:17 UTC, AlexRaptor commented on homework1/homework1/main.swift
> +func getBodyType() -> Car.Body {
- [ ] место этого метода (такой логики) внутри enum-а

2021-11-02 06:01 UTC, hellbeemzk commented
Исправлен баг для выхода из меню - достаточно нажать один раз на выход. Метод getBodyType() перемещен в enum Body.

2021-11-02 15:38 UTC, AlexRaptor requested changes

2021-11-02 15:38 UTC, AlexRaptor commented on homework1/homework1/Car.swift
> +        static func getBodyType() -> Car.Body {
- [ ] не, не так :) я же написал " место этого метода (ТАКОЙ ЛОГИКИ) внутри enum-а". Т.е. логики получения типа кузова по индексу (и притом не по строке, а Int будет лучше). А вот запрашивать ввод нужно не в энаме

2021-11-02 16:10 UTC, hellbeemzk commented on homework1/homework1/Car.swift
> +        static func getBodyType() -> Car.Body {
Исправил. Надеюсь сейчас понял Вас правильно :)

2021-11-02 16:23 UTC, AlexRaptor requested changes

2021-11-02 16:23 UTC, AlexRaptor commented on homework1/homework1/Car.swift
> +        static func getBodyType(_ bodyType: Int) -> Car.Body {
Здесь правильно

2021-11-02 16:23 UTC, AlexRaptor commented on homework1/homework1/main.swift
> +    Car.Body.printBodyTypes()
- [ ] А тут вынеси эти 3 строки в отдельный метод, возвращающий Body (не забудь про такие же строки в выводе отфильтрованного массива)
- [ ] не делай по-умолчанию значение 3. Если добавятся новые типы кузова в перечисление, придётся это значение по-умолчанию править. Сделай, например -1

2021-11-03 12:27 UTC, AlexRaptor approved these changes
👍

2021-11-03 12:29 UTC, merged