Feature/homework 3
hellbeemzk/FocusStartHomeworks pull request #3
Opened 2021-11-15 08:12 UTC by hellbeemzk

Реализовано приложение-визитка о себе

2021-11-15 12:43 UTC, c0dedbear requested changes
Симпатично сделано, мне нравится. За сколько полумарафон пробежал?)

По проекту:
- в альбомной ориентации все ломается, либо отключай либо допиливай констрейнты
- смотри комменты по коду

2021-11-15 12:43 UTC, c0dedbear commented on myCV/myCV/Application/SceneDelegate.swift
> +private extension SceneDelegate {
если делаешь приватный экстеншен все свойства и методы внутри станут приватными, не нужно дополнительно прописывать отдельно.

2021-11-15 12:43 UTC, c0dedbear commented on myCV/myCV/Application/SceneDelegate.swift
> +    private func createTabBarController() -> UITabBarController {
На будущее - в SceneDelegate не должно быть своих методов, у него есть уже своя ответственность, не нужно давать ему еще одну. Но это про архитектуры и SOLID уже...

2021-11-15 12:43 UTC, c0dedbear commented on myCV/myCV/Constants.swift
> +struct Constants {
а зачем тут статик свойства? В реальных приложениях данные практически никогда в статиках не хранятся. 
Статики в enum, либо переименовывай модель и используй ее на экранах.

2021-11-15 12:43 UTC, c0dedbear commented on myCV/myCV/SkillsVC.swift
> +//            mySwitch.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 1/8),
закомментированный код не должен попадать в пул-реквесты и тем более в основную ветку разработки.

2021-11-15 13:59 UTC, hellbeemzk commented
Прошу прощения, не углядел закомментированный код.
Не знаю почему недостаточно поставить галочку в General -> Device Orientation -> Portrait, чтобы отключить альбомную ориентацию. Пришлось пилить метод в AppDelegate для этого. 
Полумарафон пробежал за 1:50, тоже бегаешь ?)
На втором экране про опыт, надеюсь отсылку к мему ты понял, а то в противном случае я боюсь быть неправильно понятым :)

2021-11-16 04:39 UTC, c0dedbear commented
> Прошу прощения, не углядел закомментированный код.
> Не знаю почему недостаточно поставить галочку в General -> Device Orientation -> Portrait, чтобы отключить альбомную ориентацию. Пришлось пилить метод в AppDelegate для этого.
> Полумарафон пробежал за 1:50, тоже бегаешь ?)
> На втором экране про опыт, надеюсь отсылку к мему ты понял, а то в противном случае я боюсь быть неправильно понятым :)

Я бегаю, но это не основной вид спорта скажем так, как доп. кардио. пару раз в неделю. Но думаю тоже попозже пробежать полумарафон.
Да, второй экран улыбнул)

> Не знаю почему недостаточно поставить галочку в General -> Device Orientation -> Portrait, чтобы отключить альбомную ориентацию. Пришлось пилить метод в AppDelegate для этого.
Это по моему баг в xCode на симуляторе. На девайсе поидее должно быть норм.

2021-11-16 04:39 UTC, c0dedbear approved these changes
Принято

2021-11-16 04:39 UTC, merged