Feature/homework 4
hellbeemzk/FocusStartHomeworks pull request #4
Opened 2021-11-22 14:02 UTC by hellbeemzk

Реализовал приложение на основе CollectionView со списком книг, каждую из которых можно выбрать и посмотреть детальную информацию. В дополнительном модальном окне можно посмотреть оценку книги. Приложение функционирует в портретной и альбомной ориентации.

2021-11-22 17:41 UTC, c0dedbear requested changes
Сделано неплохо, да и подборка книг отличная.

Не все маг цифры унесены в константы/метрики.

2021-11-22 17:41 UTC, c0dedbear commented on CollectionApp/CollectionApp/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
забыл final

2021-11-22 17:41 UTC, c0dedbear commented on CollectionApp/CollectionApp/CollectionViewCell.swift
> +            imageBook.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 0),
здесь constant и так будет 0

2021-11-22 18:29 UTC, hellbeemzk commented on CollectionApp/CollectionApp/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
Исправлено

2021-11-22 18:29 UTC, hellbeemzk commented on CollectionApp/CollectionApp/CollectionViewCell.swift
> +            imageBook.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 0),
Исправлено

2021-11-22 18:30 UTC, hellbeemzk commented
А я думал, что 0 и 1 не являются маг цифрами и допускаются к использованию в лояуте без вынесения в константы/метрики.

2021-11-23 04:39 UTC, c0dedbear commented
> А я думал, что 0 и 1 не являются маг цифрами и допускаются к использованию в лояуте без вынесения в константы/метрики.

Является. Вообще эта практика для удобства, чтобы потом не искать в коде все эти цифры.

2021-11-23 04:39 UTC, c0dedbear approved these changes
Принято

2021-11-23 04:40 UTC, c0dedbear commented
@hellbeemzk в ветке конфликт, мердж оставляю тебе.

2021-11-23 06:14 UTC, hellbeemzk commented
Я ничего не поправлял, но, кажется, тобою вмерджилось все корректно. Проверил, в ветке develop есть проект CollectionApp с актуальными коммитами. В Форке твой мердж отображен. Не могу найти конфликт )
![merge](https://user-images.githubusercontent.com/91457160/142978408-dfa62ad7-3d25-402e-a29b-7f01c591bbf1.png)

2021-11-23 13:29 UTC, c0dedbear commented
Странно.

2021-11-29 12:40 UTC, closed without merging